### ISSUE TITLE
[Bug] monday.storage.instance.deleteItem(key) failed when key does not exist

### ISSUE THREAD

**Issue by kulaone** [mondaycom/monday-sdk-js#69]
**Describe the bug**
When trying to delete a key that does not exist, the Promise won't return and the error on the console is:
`components-fa9c6aebdcd36ea0b03a.js:1 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': function(e){var t;if(2===x){if(!c)for(c={};t=Wt.exec(a);)c[t[1].toLowerCase()]=t[2];t=c[e.toLowerCase()]}return null==t?null:t} could not be cloned.
    at B.postMessage (https://cdn.monday.com/build/components-fa9c6aebdcd36ea0b03a.js:1:148412)
    at callback (https://cdn.monday.com/build/components-fa9c6aebdcd36ea0b03a.js:1:147993)
    at Object.<anonymous> (https://cdn.monday.com/build/main-4240d31c3d88e3b4f16b.js:1:3969554)
    at c (https://cdn.monday.com/assets/lib/jquery-1.11.2-39cc7e053fb2635f0759e107fe933746213d55b818b20d9b6b6a772bdcc87ea2.js:25:22505)
    at Object.fireWith [as rejectWith] (https://cdn.monday.com/assets/lib/jquery-1.11.2-39cc7e053fb2635f0759e107fe933746213d55b818b20d9b6b6a772bdcc87ea2.js:25:23325)
    at n (https://cdn.monday.com/assets/lib/jquery-1.11.2-39cc7e053fb2635f0759e107fe933746213d55b818b20d9b6b6a772bdcc87ea2.js:27:3985)
    at XMLHttpRequest.t (https://cdn.monday.com/assets/lib/jquery-1.11.2-39cc7e053fb2635f0759e107fe933746213d55b818b20d9b6b6a772bdcc87ea2.js:27:10196)`

**Steps to reproduce**
1. Embed the SDK in an app
2. Call `monday.storage.instance.deleteItem(key)` with a key that has never been set.
3. See the request fails

**Expected behavior**
Expect the crash to be caught and return the failure in the Promise

**Context and environment**
Chrome desktop browser

**Comment by goodpilotfish** [comment]
I saw the same behavior today when working with monday.storage.instance.deleteItem.

**Comment by gregra81** [comment]
Hey @kulaone and @goodpilotfish , this should be solved now
